name: Run on EC2 Instance

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy application
      run: ./automaintenance/logcleanup/scripts/mockregister_logcleanup.sh
