name: Run clean-up of mock register logs

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run clean-up of mock register logs on EC2 instance
      run: ./automaintenance/logcleanup/scripts/mockregister_logcleanup.sh
