name: Run the auto-maintenance script

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 0 1 * *' # This will run the job at 00:00 on the 1st day of every month

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Run the script on EC2 using Session Manager
      run: |
        ./automaintenance/logcleanup/scripts/mockregister_logcleanup.sh
